server:
  port: 8080
  error.include-message: always
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/usertest
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop #eugen, not for production: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

debug: false
#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.springframework.web.servlet.DispatcherServlet: DEBUG
#    org.springframework.web.method.annotation: TRACE
#    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG
#    org.springframework.context: DEBUG
#    org.springframework.context.annotation: DEBUG
#    org.springframework.beans.factory: DEBUG